"""Added field into Ad table

Revision ID: b989d9ac6912
Revises: fc4ac584a21d
Create Date: 2024-04-18 02:32:59.412380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b989d9ac6912'
down_revision: Union[str, None] = 'fc4ac584a21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisments', sa.Column('is_hidden', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisments', 'is_hidden')
    # ### end Alembic commands ###
