"""Favorite ads table has been added

Revision ID: f9393b285a46
Revises: 551c781ae2a1
Create Date: 2024-04-09 21:43:12.315844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9393b285a46'
down_revision: Union[str, None] = '551c781ae2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_ads',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('advertisement_id', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['advertisement_id'], ['advertisments.id'], name=op.f('fk__favorite_ads__advertisement_id__advertisments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk__favorite_ads__user_id__users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'advertisement_id', name=op.f('pk__favorite_ads'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_ads')
    # ### end Alembic commands ###
