"""New field in Advertisment

Revision ID: ffec4012db33
Revises: b989d9ac6912
Create Date: 2024-05-04 01:18:20.415682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffec4012db33'
down_revision: Union[str, None] = 'b989d9ac6912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisments', sa.Column('country', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisments', 'country')
    # ### end Alembic commands ###
